/* GENERATED FROM FINAL EXCEL WORKBOOK. DO NOT EDIT VALUES MANUALLY. */
const HG_PRODUCTION_DATA = {
  "meta": {
    "source_file": "ERP_انبار_گمرک_v3_بازطراحی_18 BASE(8).xlsx",
    "imported_at": "2026-07-26",
    "counts": {
      "receipts": 19,
      "declarations": 8,
      "allocations": 10,
      "operations": 6,
      "vessels": 4,
      "projects": 1,
      "items": 1,
      "warehouses": 1,
      "customs": 1,
      "events": 10,
      "nature_determinations": 2
    },
    "totals": {
      "root_initial_weight": 100707.83,
      "effective_allocations": 86019.643,
      "calculated_inventory": 14688.187
    }
  },
  "receipts": [
    {
      "receipt_no": "632",
      "internal_id": "REC-00001",
      "type": "اصلی",
      "parent_id": null,
      "root_id": "632",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 59872.87,
      "source_consumed_weight": 0.0,
      "source_inventory": 59872.87,
      "source_status": "تکمیل شده",
      "status": "تقسیم شده",
      "date": "1403/11/10",
      "notes": "",
      "source_row": 2
    },
    {
      "receipt_no": "648",
      "internal_id": "REC-00002",
      "type": "اظهاری",
      "parent_id": "632",
      "root_id": "632",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 49999.287,
      "source_consumed_weight": 49999.287,
      "source_inventory": 0.0,
      "source_status": "تکمیل شده",
      "status": "بسته",
      "date": "1403/11/15",
      "notes": "",
      "source_row": 3
    },
    {
      "receipt_no": "649",
      "internal_id": "REC-00003",
      "type": "مانده",
      "parent_id": "632",
      "root_id": "632",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 9873.583,
      "source_consumed_weight": 0.0,
      "source_inventory": 9873.583,
      "source_status": "تکمیل شده",
      "status": "تقسیم شده",
      "date": "1403/11/15",
      "notes": "",
      "source_row": 4
    },
    {
      "receipt_no": "709",
      "internal_id": "REC-00004",
      "type": "اظهاری",
      "parent_id": "649",
      "root_id": "632",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 7500.0,
      "source_consumed_weight": 7500.0,
      "source_inventory": 0.0,
      "source_status": "تکمیل شده",
      "status": "بسته",
      "date": "1403/12/01",
      "notes": "",
      "source_row": 5
    },
    {
      "receipt_no": "710",
      "internal_id": "REC-00005",
      "type": "مانده",
      "parent_id": "649",
      "root_id": "632",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 2373.583,
      "source_consumed_weight": 2373.583,
      "source_inventory": 0.0,
      "source_status": "تکمیل شده",
      "status": "بسته",
      "date": "1403/12/01",
      "notes": "",
      "source_row": 6
    },
    {
      "receipt_no": "641",
      "internal_id": "REC-00006",
      "type": "اصلی",
      "parent_id": null,
      "root_id": "641",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 18076.21,
      "source_consumed_weight": 0.0,
      "source_inventory": 18076.21,
      "source_status": "تکمیل شده",
      "status": "تقسیم شده",
      "date": "1403/12/02",
      "notes": "",
      "source_row": 7
    },
    {
      "receipt_no": "646",
      "internal_id": "REC-00007",
      "type": "اظهاری",
      "parent_id": "641",
      "root_id": "641",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 7499.486,
      "source_consumed_weight": 7499.486,
      "source_inventory": 0.0,
      "source_status": "تکمیل شده",
      "status": "بسته",
      "date": "1403/12/03",
      "notes": "",
      "source_row": 8
    },
    {
      "receipt_no": "647",
      "internal_id": "REC-00008",
      "type": "مانده",
      "parent_id": "641",
      "root_id": "641",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 10576.724,
      "source_consumed_weight": 0.0,
      "source_inventory": 10576.724,
      "source_status": "تکمیل شده",
      "status": "تقسیم شده",
      "date": "1403/12/04",
      "notes": "",
      "source_row": 9
    },
    {
      "receipt_no": "717",
      "internal_id": "REC-00009",
      "type": "اظهاری",
      "parent_id": "647",
      "root_id": "641",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 3047.287,
      "source_consumed_weight": 3047.287,
      "source_inventory": 0.0,
      "source_status": "تکمیل شده",
      "status": "بسته",
      "date": "1403/12/04",
      "notes": "",
      "source_row": 10
    },
    {
      "receipt_no": "718",
      "internal_id": "REC-00010",
      "type": "مانده",
      "parent_id": "647",
      "root_id": "641",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 7529.437,
      "source_consumed_weight": 0.0,
      "source_inventory": 7529.437,
      "source_status": "تکمیل شده",
      "status": "تقسیم شده",
      "date": "1403/12/04",
      "notes": "",
      "source_row": 11
    },
    {
      "receipt_no": "698",
      "internal_id": "REC-00011",
      "type": "اصلی",
      "parent_id": null,
      "root_id": "698",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 22758.75,
      "source_consumed_weight": 0.0,
      "source_inventory": 22758.75,
      "source_status": "فعال",
      "status": "تقسیم شده",
      "date": "1403/12/04",
      "notes": "",
      "source_row": 12
    },
    {
      "receipt_no": "721",
      "internal_id": "REC-00012",
      "type": "اظهاری",
      "parent_id": "718",
      "root_id": "641",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 4579.13,
      "source_consumed_weight": 4579.13,
      "source_inventory": 0.0,
      "source_status": "تکمیل شده",
      "status": "بسته",
      "date": "1403/12/04",
      "notes": "",
      "source_row": 13
    },
    {
      "receipt_no": "722",
      "internal_id": "REC-00013",
      "type": "مانده",
      "parent_id": "718",
      "root_id": "641",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 2950.307,
      "source_consumed_weight": 2950.307,
      "source_inventory": 0.0,
      "source_status": "تکمیل شده",
      "status": "بسته",
      "date": "1403/12/04",
      "notes": "",
      "source_row": 14
    },
    {
      "receipt_no": "723",
      "internal_id": "REC-00014",
      "type": "اظهاری",
      "parent_id": "698",
      "root_id": "698",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 570.563,
      "source_consumed_weight": 570.563,
      "source_inventory": 0.0,
      "source_status": "تکمیل شده",
      "status": "بسته",
      "date": "1403/12/04",
      "notes": "",
      "source_row": 15
    },
    {
      "receipt_no": "724",
      "internal_id": "REC-00015",
      "type": "مانده",
      "parent_id": "698",
      "root_id": "698",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 22188.187,
      "source_consumed_weight": 0.0,
      "source_inventory": 22188.187,
      "source_status": "تکمیل شده",
      "status": "تقسیم شده",
      "date": "1403/12/04",
      "notes": "",
      "source_row": 16
    },
    {
      "receipt_no": "725",
      "internal_id": "REC-00016",
      "type": "اظهاری",
      "parent_id": "724",
      "root_id": "698",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 6479.13,
      "source_consumed_weight": 6479.13,
      "source_inventory": 0.0,
      "source_status": "تکمیل شده",
      "status": "بسته",
      "date": "1403/12/04",
      "notes": "",
      "source_row": 17
    },
    {
      "receipt_no": "726",
      "internal_id": "REC-00017",
      "type": "مانده",
      "parent_id": "724",
      "root_id": "698",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 15709.057,
      "source_consumed_weight": 0.0,
      "source_inventory": 15709.057,
      "source_status": "تکمیل شده",
      "status": "تقسیم شده",
      "date": "1403/12/04",
      "notes": "",
      "source_row": 18
    },
    {
      "receipt_no": "727",
      "internal_id": "REC-00018",
      "type": "اظهاری",
      "parent_id": "726",
      "root_id": "698",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 1020.87,
      "source_consumed_weight": 1020.87,
      "source_inventory": 0.0,
      "source_status": "تکمیل شده",
      "status": "بسته",
      "date": "1403/12/04",
      "notes": "",
      "source_row": 19
    },
    {
      "receipt_no": "728",
      "internal_id": "REC-00019",
      "type": "مانده",
      "parent_id": "726",
      "root_id": "698",
      "item": "کلینکر سیمان",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "warehouse": "انبار اصلی مند دشتی",
      "initial_weight": 14688.187,
      "source_consumed_weight": 0.0,
      "source_inventory": 14688.187,
      "source_status": "تکمیل شده",
      "status": "فعال",
      "date": "1403/12/04",
      "notes": "",
      "source_row": 20
    }
  ],
  "declarations": [
    {
      "declaration_no": "DEC-00001",
      "koutaj_no": "2148",
      "date": "1404/11/27",
      "vessel_name": "M/V VIGOROUS",
      "operation_id": "OP-1405-0001",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "status": "تکمیل شده",
      "notes": "",
      "source_row": 2
    },
    {
      "declaration_no": "DEC-00002",
      "koutaj_no": "2151",
      "date": "1404/12/02",
      "vessel_name": "M/V MEHDI12",
      "operation_id": "OP-1405-0002",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "status": "تکمیل شده",
      "notes": "",
      "source_row": 3
    },
    {
      "declaration_no": "DEC-00003",
      "koutaj_no": "2528",
      "date": "1405/04/11",
      "vessel_name": "M/V MEHDI12",
      "operation_id": "OP-1405-0003",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "status": "تکمیل شده",
      "notes": "",
      "source_row": 4
    },
    {
      "declaration_no": "DEC-00004",
      "koutaj_no": "2561",
      "date": "1405/04/21",
      "vessel_name": "M/V IMAN10",
      "operation_id": "OP-1405-0004",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "status": "تکمیل شده",
      "notes": "",
      "source_row": 5
    },
    {
      "declaration_no": "DEC-00005",
      "koutaj_no": "2573",
      "date": "1405/04/29",
      "vessel_name": "M/V BOUSHEHR",
      "operation_id": "OP-1405-0005",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "status": "تکمیل شده",
      "notes": "",
      "source_row": 6
    },
    {
      "declaration_no": "DEC-00006",
      "koutaj_no": "2576",
      "date": "1405/04/29",
      "vessel_name": "M/V BOUSHEHR",
      "operation_id": "OP-1405-0005",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "status": "تکمیل شده",
      "notes": "",
      "source_row": 7
    },
    {
      "declaration_no": "DEC-00007",
      "koutaj_no": "2588",
      "date": "1405/05/01",
      "vessel_name": "M/V MEHDI12",
      "operation_id": "OP-1405-0006",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "status": "در حال عملیات",
      "notes": "",
      "source_row": 8
    },
    {
      "declaration_no": "DEC-00008",
      "koutaj_no": "2594",
      "date": "1405/05/01",
      "vessel_name": "M/V MEHDI12",
      "operation_id": "OP-1405-0006",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "status": "در حال عملیات",
      "notes": "",
      "source_row": 9
    }
  ],
  "allocations": [
    {
      "id": "ASN-00001",
      "receipt_no": "648",
      "declaration_no": "DEC-00001",
      "koutaj_no": "2148",
      "weight": 49999.287,
      "status": "تکمیل شده",
      "effective_status": "تکمیل شده",
      "operation_id": "OP-1405-0001",
      "date": null,
      "notes": "",
      "source_row": 2
    },
    {
      "id": "ASN-00002",
      "receipt_no": "646",
      "declaration_no": "DEC-00002",
      "koutaj_no": "2151",
      "weight": 7499.486,
      "status": "تکمیل شده",
      "effective_status": "تکمیل شده",
      "operation_id": "OP-1405-0002",
      "date": null,
      "notes": "",
      "source_row": 3
    },
    {
      "id": "ASN-00003",
      "receipt_no": "709",
      "declaration_no": "DEC-00003",
      "koutaj_no": "2528",
      "weight": 7500.0,
      "status": "تکمیل شده",
      "effective_status": "تکمیل شده",
      "operation_id": "OP-1405-0003",
      "date": null,
      "notes": "",
      "source_row": 4
    },
    {
      "id": "ASN-00004",
      "receipt_no": "710",
      "declaration_no": "DEC-00004",
      "koutaj_no": "2561",
      "weight": 2373.583,
      "status": "تکمیل شده",
      "effective_status": "تکمیل شده",
      "operation_id": "OP-1405-0004",
      "date": null,
      "notes": "",
      "source_row": 5
    },
    {
      "id": "ASN-00005",
      "receipt_no": "717",
      "declaration_no": "DEC-00004",
      "koutaj_no": "2561",
      "weight": 3047.287,
      "status": "تکمیل شده",
      "effective_status": "تکمیل شده",
      "operation_id": "OP-1405-0004",
      "date": null,
      "notes": "",
      "source_row": 6
    },
    {
      "id": "ASN-00006",
      "receipt_no": "721",
      "declaration_no": "DEC-00005",
      "koutaj_no": "2573",
      "weight": 4579.13,
      "status": "تکمیل شده",
      "effective_status": "تکمیل شده",
      "operation_id": "OP-1405-0005",
      "date": null,
      "notes": "",
      "source_row": 7
    },
    {
      "id": "ASN-00007",
      "receipt_no": "722",
      "declaration_no": "DEC-00006",
      "koutaj_no": "2576",
      "weight": 2950.307,
      "status": "تکمیل شده",
      "effective_status": "تکمیل شده",
      "operation_id": "OP-1405-0005",
      "date": null,
      "notes": "",
      "source_row": 8
    },
    {
      "id": "ASN-00008",
      "receipt_no": "723",
      "declaration_no": "DEC-00006",
      "koutaj_no": "2576",
      "weight": 570.563,
      "status": "تکمیل شده",
      "effective_status": "تکمیل شده",
      "operation_id": "OP-1405-0005",
      "date": null,
      "notes": "",
      "source_row": 9
    },
    {
      "id": "ASN-00009",
      "receipt_no": "725",
      "declaration_no": "DEC-00007",
      "koutaj_no": "2588",
      "weight": 6479.13,
      "status": "تکمیل شده",
      "effective_status": "در حال عملیات",
      "operation_id": "OP-1405-0006",
      "date": null,
      "notes": "",
      "source_row": 10
    },
    {
      "id": "ASN-00010",
      "receipt_no": "727",
      "declaration_no": "DEC-00008",
      "koutaj_no": "2594",
      "weight": 1020.87,
      "status": "تکمیل شده",
      "effective_status": "در حال عملیات",
      "operation_id": "OP-1405-0006",
      "date": null,
      "notes": "",
      "source_row": 11
    }
  ],
  "operations": [
    {
      "id": "OP-1405-0001",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "item": "کلینکر سیمان",
      "vessel_name": "M/V VIGOROUS",
      "type": "بارگیری صادرات",
      "date": "1404/11/28",
      "eta": null,
      "nor": null,
      "start_date": null,
      "end_date": null,
      "exit_date": "1404/12/07",
      "status": "تکمیل شده",
      "description": "بارگیری صادرات — M/V VIGOROUS",
      "source_row": 2
    },
    {
      "id": "OP-1405-0002",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "item": "کلینکر سیمان",
      "vessel_name": "M/V MEHDI12",
      "type": "بارگیری صادرات",
      "date": "1404/12/03",
      "eta": null,
      "nor": null,
      "start_date": null,
      "end_date": null,
      "exit_date": "1404/02/08",
      "status": "تکمیل شده",
      "description": "بارگیری صادرات — M/V MEHDI12",
      "source_row": 3
    },
    {
      "id": "OP-1405-0003",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "item": "کلینکر سیمان",
      "vessel_name": "M/V MEHDI12",
      "type": "بارگیری صادرات",
      "date": "1405/04/12",
      "eta": null,
      "nor": null,
      "start_date": null,
      "end_date": null,
      "exit_date": "1405/04/18",
      "status": "تکمیل شده",
      "description": "بارگیری صادرات — M/V MEHDI12",
      "source_row": 4
    },
    {
      "id": "OP-1405-0004",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "item": "کلینکر سیمان",
      "vessel_name": "M/V IMAN10",
      "type": "بارگیری صادرات",
      "date": "1405/04/22",
      "eta": null,
      "nor": null,
      "start_date": null,
      "end_date": null,
      "exit_date": "1405/04/25",
      "status": "تکمیل شده",
      "description": "بارگیری صادرات — M/V IMAN10",
      "source_row": 5
    },
    {
      "id": "OP-1405-0005",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "item": "کلینکر سیمان",
      "vessel_name": "M/V BOUSHEHR",
      "type": "بارگیری صادرات",
      "date": "1405/04/29",
      "eta": null,
      "nor": null,
      "start_date": null,
      "end_date": null,
      "exit_date": "1405/05/03",
      "status": "تکمیل شده",
      "description": "بارگیری صادرات — M/V BOUSHEHR",
      "source_row": 6
    },
    {
      "id": "OP-1405-0006",
      "project": "صادرات کلینکر سیمان مند دشتی",
      "item": "کلینکر سیمان",
      "vessel_name": "M/V MEHDI12",
      "type": "بارگیری صادرات",
      "date": "1405/04/31",
      "eta": null,
      "nor": null,
      "start_date": null,
      "end_date": null,
      "exit_date": null,
      "status": "در حال عملیات",
      "description": "بارگیری صادرات — M/V MEHDI12",
      "source_row": 7
    }
  ],
  "vessels": [
    {
      "id": "VES-0001",
      "vessel_name": "M/V MEHDI12",
      "notes": "شناور صادرات کلینکر",
      "loaded_weight": null
    },
    {
      "id": "VES-0002",
      "vessel_name": "M/V VIGOROUS",
      "notes": "شناور صادرات کلینکر",
      "loaded_weight": null
    },
    {
      "id": "VES-0003",
      "vessel_name": "M/V IMAN10",
      "notes": "شناور صادرات کلینکر",
      "loaded_weight": null
    },
    {
      "id": "VES-0004",
      "vessel_name": "M/V BOUSHEHR",
      "notes": "شناور صادرات کلینکر",
      "loaded_weight": null
    }
  ],
  "projects": [
    {
      "id": "PRJ-0001",
      "name": "صادرات کلینکر سیمان مند دشتی",
      "description": "پروژه صادرات کلینکر"
    }
  ],
  "items": [
    {
      "id": "ITM-0001",
      "name": "کلینکر سیمان",
      "unit": "تن"
    }
  ],
  "warehouses": [
    {
      "id": "WH-0001",
      "name": "دانیال نوین",
      "description": "انبار اصلی پروژه"
    }
  ],
  "customs": [
    {
      "id": "CUS-0001",
      "name": "گمرک منطقه ویژه پارسیان",
      "description": "گمرک اصلی"
    }
  ],
  "events": [
    {
      "id": "1",
      "date": "1403/11/10",
      "type": "ورود شناور",
      "operation_id": null,
      "receipt_no": null,
      "description": ""
    },
    {
      "id": "2",
      "date": "1403/11/10",
      "type": "صدور قبض",
      "operation_id": null,
      "receipt_no": "632",
      "description": ""
    },
    {
      "id": "3",
      "date": "1403/11/15",
      "type": "تفکیک قبض",
      "operation_id": null,
      "receipt_no": "632",
      "description": ""
    },
    {
      "id": "4",
      "date": "1403/11/20",
      "type": "اظهار گمرکی",
      "operation_id": "OP-1405-0001",
      "receipt_no": "648",
      "description": ""
    },
    {
      "id": "5",
      "date": "1403/12/01",
      "type": "تفکیک قبض",
      "operation_id": null,
      "receipt_no": "649",
      "description": ""
    },
    {
      "id": "6",
      "date": "1403/12/05",
      "type": "اظهار گمرکی",
      "operation_id": "OP-1405-0002",
      "receipt_no": "632",
      "description": ""
    },
    {
      "id": "7",
      "date": "1404/01/10",
      "type": "اظهار گمرکی",
      "operation_id": "OP-1405-0001",
      "receipt_no": "709",
      "description": ""
    },
    {
      "id": "8",
      "date": "1404/01/15",
      "type": "نامه گمرک",
      "operation_id": "OP-1405-0001",
      "receipt_no": null,
      "description": ""
    },
    {
      "id": "9",
      "date": "1404/01/20",
      "type": "تعیین ماهیت",
      "operation_id": "OP-1405-0001",
      "receipt_no": null,
      "description": ""
    },
    {
      "id": "10",
      "date": "1404/01/26",
      "type": "خروج کالا",
      "operation_id": "OP-1405-0001",
      "receipt_no": null,
      "description": ""
    }
  ],
  "nature_determinations": [
    {
      "id": "1",
      "request_no": "REQ-00001",
      "customs_doc_no": "DOC-1403-001",
      "date": "1404/01/15",
      "receipt_no": "REC-00001",
      "operation_id": "OP-1405-0001",
      "subject": "تعیین ماهیت کلینکر صادراتی",
      "status": "تکمیل شده",
      "result": "تایید صادرات",
      "response_date": "1404/01/18"
    },
    {
      "id": "2",
      "request_no": "REQ-00002",
      "customs_doc_no": "DOC-1403-002",
      "date": "1404/02/05",
      "receipt_no": "REC-00003",
      "operation_id": "OP-1405-0002",
      "subject": "تعیین ماهیت کلینکر صادراتی",
      "status": "در حال بررسی",
      "result": "-",
      "response_date": "-"
    }
  ]
};
